-- Cars and bookings schema, ported from Prisma + SQLite.
-- Column names are kept in camelCase (quoted) so the app code can read
-- rows directly from supabase-js without per-field renaming.

create table public.cars (
  id bigint generated by default as identity primary key,
  make text not null,
  model text not null,
  year int not null,
  "pricePerDay" double precision not null,
  status text not null default 'Available'
    check (status in ('Available', 'Maintenance', 'Retired')),
  "imagePath" text not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.bookings (
  id bigint generated by default as identity primary key,
  "carId" bigint not null
    references public.cars(id) on delete restrict on update cascade,
  "customerName" text not null,
  "startDate" date not null,
  "endDate" date not null,
  "totalPrice" double precision not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index bookings_car_id_idx on public.bookings ("carId");

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$ language plpgsql;

create trigger cars_set_updated_at
  before update on public.cars
  for each row execute function public.set_updated_at();

create trigger bookings_set_updated_at
  before update on public.bookings
  for each row execute function public.set_updated_at();

alter table public.cars enable row level security;
alter table public.bookings enable row level security;

-- Public gallery: anon can list/read cars marked Available.
create policy "anon can read available cars"
  on public.cars for select
  to anon
  using (status = 'Available');

-- Authenticated users see the full fleet (admin reads still go through
-- the service role, which bypasses RLS, but this keeps the policy
-- explicit for any future logged-in views).
create policy "authenticated can read all cars"
  on public.cars for select
  to authenticated
  using (true);

-- Bookings have no public-facing policies. All reads/writes happen via
-- server actions using the service role.
